config/routes.rb
Rails.application.routes.draw do
  
 
  devise_for :users
  
  

  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  
  
  resources :users do
    member do
      patch 'update', to: 'users#update'
      get :edit
    end
  end
 

  resources :bugs do 
    member do 
      get :assign
      get :assign_users
      
    end
  end
  get 'comments/new', to: 'comments#new'
  post 'comments', to: 'comments#create'
  
 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord
    has_many :comments
    belongs_to :user
    validates :title, :description, :priority, :Completiontime, presence: true

    default_scope ->{ order(created_at: :desc) }

    # attr_accessor :assign
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :role, presence: true
  has_many :bugs
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable,:confirmable, :rememberable, :validatable

         def manager?
          role == 'manager'
        end
      
        def qa?
          role == 'qa'
        end
        
        def developer?
          role == 'developer'
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
    end


   
end

app/controllers/bugs_controller.rb
class BugsController <ApplicationController
    def new
      # Manager and QA can create bugs
        if current_user.role == "developer"
          flash[:danger] = "You don't have permission to perform this operation"
          redirect_to bugs_path
        else
          @bug = Bug.new
        end 
    end

    def index 
      if current_user.role =="manager"
        @bugs = Bug.all
      else
        if current_user.role == "developer"
          @bugs = Bug.where(assign_to: current_user.id)
        else
          @bugs = current_user.bugs
        end
      end

    end
    
    def create
      # Manager % @users.each do |user| %>
          
         
      return if current_user.role == "developer"
       @bug = current_user.bugs.new(bug_params)
        if @bug.save
             redirect_to bugs_path
        else
           render 'new'
        end
    end  

    def edit
      # the person who has created the bug can edit the bug and manager can edit all bugs
      bug = Bug.find_by(id: params[:id])
      if bug 
        if current_user.id != bug.user_id && current_user.role != "manager"
          flash[:danger] = "You don't have permission to perform this operation"
          redirect_to bugs_path
        else
        @bug = bug
        end
      else
        redirect_to root_path
      end
    end

    def update
      # the person who has created the bug can edit the bug and manager can edit all bugs
      @bug = Bug.find(params[:id])
      if @bug.update(bug_params)
        flash[:success] = "Bug updated"
        redirect_to bugs_path
        # Handle a successful update.
      else
        render 'edit'
      end
    end


    def show
      bug = Bug.find_by!(bug: params[:id])
      redirect_to bug_path
    end

       
    def assign
      # Manager can assign bug
      if current_user.role == "developer" || current_user.role == "qa"
        flash[:danger] = "You don't have permission to perform this operation"
        redirect_to bugs_path
      else
            @bug = Bug.find(params[:id])
            @users = User.where("role IN ('qa', 'developer')").pluck(:email, :role, :id)
            @users.each do |user|
              user[0] = "#{user[0]} - #{user[1]}"              
        end 
      end
      
    end

   

      def destroy
        # manager can delete bug and the person who created the bug can delete it
        if current_user.role== "developer"
            flash[:danger] = "You don't have permission to perform this operation"
          redirect_to bugs_path
          else
          bug = Bug.find_by_id params[:id]
          bug.destroy
          flash[:success] = "Bug deleted"
          redirect_to bugs_path
        end  
      end 
     
        def assign_users
          #manager and qa can assign bug
          
          @bug = Bug.find_by(id: params[:id])
          if @bug.update(assign_to: params[:assign_users])
            flash[:success] = "Bug assigned successfully"
            redirect_to   bugs_path
          else
            flash[:danger] = "Something went wrong, please try again!"
            redirect_to assign_bug_path(params[:id])
          end
        end 

    private
      
    def bug_params
      params.require(:bug).permit(:title, :description, :priority, :Completiontime)
    end

    def authorize_bug
      if @bug.present?
        authorize @bug
      else
        flash[:danger] = "Something went wrong, please try again!"
      end
     
    end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
     def new
        if current_user.role == "qa"
            flash[:danger] = "You don't have permission to perform this operation"
            redirect_to bugs_path
        else
            @bug_id = params[:id]
        end
      end

    def create
        @bug = Bug.find(params[:bug_id])
        @bug.comments.create(comment_params)
        redirect_to bugs_path
    end

   

    private

    def comment_params
        params.permit(:text)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.where.not(role: "manager")
    end
    
   def edit
    @user = User.find_by(id: params[:id])
    
   end


    def update
        @user = User.find(params[:id])
        if @user.update(role: params[:role])
            flash[:success] = "Role  updated"
        end  
        redirect_to users_path

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/bugs/_form.html.erb
<%= form_for @bug do |f| %>
<div class="form-contol">
    <%=f.label :title,'Title: ', :class=>"col-form-label col-md-1" %>
    <%= f.text_field :title, :class => 'col-md-11 form-control', :required => true %>
</div>
<br/>
  <div class="">
    <%=f.label :description , 'Description: ' %>
    <%=f.text_area :description , :class => "form-control" %>
  </div>

 <br/>
  
  <div class="priority-field">
  <%= f.select :priority, options_for_select([["Select Priority", ""],["High", "High"], ["Medium", "Medium"], ["Low", "Low"]]) %> 
  </div>
  <br/>
  
  <div class="time-field">
  <%= f.select :Completiontime, options_for_select([["Select Completiontime", ""],["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"]]) %> 
  </div>
  <br/>

  <div class="actions">
    <%= f.submit "Create" %>
  </div>

  <%end%>

app/views/bugs/assign.html.erb
<h1>Assign bug to user</h1>
    <%= form_with url:  assign_users_bug_path(@bug.id) ,method: :get, local: true do |form| %>
       <div class="assign-field">
       
        <%= form.select :assign_users, options_for_select(@users), {} , { class: "form-control " }  %>
        </div>
        <br/>
         <div class="actions">
        <%= form.submit "Submit" %>
       </div>
  <% end %>

app/views/bugs/edit.html.erb
<div class="container">
		<h1>Update the bug</h1>
		<%= form_for @bug do |f| %>
<div class="form-contol">
    <%=f.label :title,'Title: ', :class=>"col-form-label col-md-1" %>
    <%= f.text_field :title, :class => 'col-md-11 form-control', :required => true %>
</div>
<br/>
  <div class="">
    <%=f.label :description , 'Description: ' %>
    <%=f.text_area :description , :class => "form-control" %>
  </div>

 <br/>
 <div class="actions">
    <%= f.submit "Create" %>
  </div>

  <%end%>
</div>

app/views/bugs/index.html.erb
<div class="container" >
 <h1> Welcome to the Bugs Page</h1>
  <br/>
  <br/>
  <br/>
    <table class="table">
    <tbody>
    <thead class="thead-light">
    <% @bugs.each do |bug| %>
    
    <tr>
        
         <td><h3> Title: </h3>  <%= bug.title%></td>
         <td><h3>  Description: </h3> <%= bug.description %></td>
         <td><h3>  Priority: </h3>  <%= bug.priority %> </td>
         <td><h3>  Deadline Days: </h3> <%= bug.Completiontime %></td>
          <td><h3>   Status: </h3> <%= bug.status %></td>
        <td>
          <div>
          <% bug.comments.any? && bug.comments.each do |comment| %>
          <%= comment.text %>
          <% end %>
        </div>
        </td>
         
      <th> <%= link_to "DELETE Bug", bug_path(bug.id), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %></th>
        <th> <%= link_to "Edit Bug",  edit_bug_path(bug.id),  class: "btn btn-primary" %> </th>
          <% if current_user.role == "manager" %>
          <th> <%= link_to "Assign to",  assign_bug_path(bug.id),    class: "btn btn-primary" %> </th>
          <% end %>
          
         <th> <%= link_to "Add Comment",  "/comments/new?id=#{bug.id}",  class: "btn btn-success" %> </th>
        
         <% end %>
    </tr>
    </table>
   
    
</div>
 






    

app/views/bugs/new.html.erb
<div class ="container">
    <p class ="alert"></p>
    <div class="container">
        <h2>Create new bug </h2>
            <br/>

        <%= render 'form' %>
    </div>
</div>

app/views/bugs/show.html.erb
<h1>Hello World</h1>

app/views/comments/new.html.erb
<h2>Add a Comment </h2>
<%= form_with url: comments_path, method: :post  do |f| %>
    <%= f.hidden_field :bug_id, value: @bug_id %>
    <%= f.text_area :text, placeholder: "Add comment" %>
    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
<div class ="footer-content">
<nav>
<h3>BUGZILLA </h3>
<p>This is my test project of BUGZILLA app where you<br/>can create  update  delete & assign the bug.</p>
<ul class ="links">
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<li><a href="https://euphoriaxr.com/">Click here</a></li>
</ul>
</nav>
</div>
</footer>

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
<%= link_to "Bugzilla App", home_path, id: "logo" %>
<nav>
<ul class="nav navbar-nav navbar-right">
<li><%= link_to "Home", home_path %></li>
<li><%= link_to "Help", help_path %></li>
<% if user_signed_in? %>
    <li><%= link_to "Create Bug",   new_bug_path %></li>
     <li><%= link_to "Show Bugs",   bugs_path %></li>
     <% if current_user.role == "manager" %>
      <li><%= link_to "Show Users",   users_path %></li>
      <% end %>

    <li><%= link_to "Sign out",    destroy_user_session_path , method: :delete%></li> 
    
<% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
<% end %>
</ul>
</nav>
</div>

</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script
src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.j
s">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= yield(:title) %> | Rails Bugzilla App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class="container mt-100">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %> </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About Page</h1>
<head>
<title><%= yield(:title) %> | Rails Bugz App</title>
</head>
<body>
<h3>To know about the project><a href="https://euphoriaxr.com/">Click here</a></h3>
</body>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<h3>To Contact us Visit our Webiste or send us a mail</h3>
<a href="https://euphoriaxr.com/">Click here</a>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<head>
<title><%= yield(:title) %> | Rails Bugz App</title>
</head>
<body>
<h3>To know about the project><a href="https://euphoriaxr.com/">Click here</a></h3>
</body>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
<h1>EuphoriaXr</h1>
<head>
<title><%= yield(:title) %> | Rails Bugz App</title>
</head>
<h2>Welcome to my Bugzilla app</h2>


<% if user_signed_in? %>
  <%= link_to "Edit Profile!",  edit_user_registration_path, class: "btn btn-lg btnprimary" %>
<% else %>
<%= link_to "Sign up now!",  new_user_registration_path, class: "btn btn-lg btnprimary" %>
<%= link_to "Sign in!",  new_user_session_path, class: "btn btn-lg btnprimary" %>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Hello world</h1>
<%= form_with url:  user_path(@user.id), method: :patch,local: true do |form| %>
    <table class="table">
        <tbody>
            <tr>
                <td> <h3>Role: </h3> <%= @user.role %> </td>
                <td> <%= form.select :role, options_for_select([["Select Role", ""],["manager", "manager"], ["qa", "qa"], ["developer", "developer"]]) %> </td> 
                <td><%= form.submit  %></td>
            </tr>
        </tbody>
    </table>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>
<div class="container" >
 
  <br/>
  <br/>
  <br/>
 
<table class="table">
    <tbody>
        <thead class="thead-light">
          <% @users.each do |user| %>
          
            <tr>
              <td> <h3>Name: </h3> <%= user.name %></td>
              <td> <h3>Email: </h3>  <%= user.email %></td>
              <td> <h3>Role: </h3> <%= user.role %> </td>
              <td><%= link_to 'Change Role', edit_user_path(user.id), class: "btn btn-primary" %></td>
              
                <% end %>
            </tr>
        </thead>      
    </tbody>
</table>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>